include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - use_super_parameters
    - prefer_relative_imports
    - cancel_subscriptions
    - always_declare_return_types
    - avoid_bool_literals_in_conditional_expressions
    - avoid_escaping_inner_quotes
    - cascade_invocations
    - eol_at_end_of_file
    - leading_newlines_in_multiline_strings
    - unnecessary_parenthesis
    - unnecessary_raw_strings
