name: aluno_uepb
description: An App for UEPB students

publish_to: "none"

version: 1.2.2+8

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  shared_preferences: ^2.0.6
  open_file: ^3.2.1
  workmanager: ^0.4.1
  rxdart: ^0.27.1
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0
  firebase_analytics: ^8.1.2
  cloud_firestore: ^2.3.0
  flutter_native_timezone: ^2.0.0
  timezone: ^0.7.0
  intl: ^0.17.0
  flutter_local_notifications: ^6.0.0
  fl_chart: ^0.36.2
  cupertino_icons: ^1.0.2
  html: ^0.15.0
  http: ^0.13.1
  hive_flutter: ^1.1.0
  hive: ^2.0.4  
  flutter_modular: ^3.3.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_native_splash: ^1.2.0
  mockito: ^5.0.4
  modular_codegen: ^3.0.0
  mobx_codegen: ^2.0.1+3
  build_runner: ^1.12.2
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#fafafa"
  image: images/splash.png
  color_dark: "#1a1a1a"
  image_dark: images/splah-invert.png
  android: true
  android_gravity: 'center'

flutter:
  uses-material-design: true
  assets:
    - images/icon.png

