name: aluno_uepb
description: Aplicativo não oficial para alunos da UEPB

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.1
  html:
  hive_flutter: ^0.3.0+2
  hive: ^1.4.1+1
  path_provider:
  provider:
  cupertino_icons:
  firebase_analytics: ^5.0.16
  cloud_firestore: ^0.13.7
  diacritic: ^0.1.1
  fl_chart: ^0.10.1
  flutter_colorpicker: ^0.3.4
  flutter_local_notifications: ^1.4.4+4
  weekday_selector: ^0.4.0
  rxdart: ^0.23.1
  flutter_localizations:
    sdk: flutter

dependency_overrides:
  path: ^1.6.4
  dartx: ^0.3.0
  characters: 1.0.0
  collection: 1.14.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.0+2
  build_runner: ^1.10.0

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
#  assets:
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  
