name: aluno_uepb
description: Aplicativo não oficial para alunos da UEPB

publish_to: "none"

version: 1.1.0

## Slidy Scripts 
vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner
scripts:
  mobx_build: $runner build
  mobx_watch: $clean & $get & $runner watch
  mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs



environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  firebase_core: ^0.7.0
  cloud_firestore: ^0.16.0
  firebase_analytics: ^7.0.1
  screenshot: ^0.2.0
  permission_handler: ^5.0.1+1
  image_gallery_saver: ^1.6.7
  flutter_native_timezone: ^1.0.4
  intl: ^0.16.1
  charts_flutter: ^0.9.0
  rxdart: ^0.25.0
  device_info: ^1.0.0
  flutter_local_notifications: ^3.0.3
  weekday_selector: ^0.4.0
  flutter_colorpicker: ^0.3.5
  fl_chart: ^0.12.2
  cupertino_icons: ^1.0.2
  html: ^0.14.0+4
  http: ^0.12.2
  hive_flutter: ^0.3.1
  hive: ^1.4.4+1
  diacritic: ^0.1.1
  flutter_mobx: ^1.1.0+2
  mobx: ^1.2.1+4
  flutter_modular: ^2.0.1
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_native_splash: ^0.2.7
  mockito: ^4.1.3
  modular_codegen: ^2.1.0
  mobx_codegen: ^1.1.2
  build_runner: ^1.10.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/icon.png

