name: aluno_uepb
description: Aplicativo não oficial para alunos da UEPB

publish_to: "none"

version: 1.1.0

## Slidy Scripts 
vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner
scripts:
  mobx_build: $runner build
  mobx_watch: $clean & $get & $runner watch
  mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0
  asuka: ^2.0.0-nullsafety.2
  firebase_core: ^1.0.3
  cloud_firestore: ^1.0.5
  firebase_analytics: ^8.0.0
  screenshot: ^1.0.0-nullsafety.1
  permission_handler: ^6.1.3
  gallery_saver: ^2.1.0
  flutter_native_timezone: ^1.0.10
  timezone: ^0.7.0
  intl: ^0.17.0
  rxdart: ^0.26.0
  device_info: ^2.0.0
  flutter_local_notifications: ^5.0.0+1
  weekday_selector: ^1.0.0
  flutter_colorpicker: ^0.4.0
  fl_chart: ^0.35.0
  cupertino_icons: ^1.0.2
  html: ^0.15.0
  http: ^0.13.1
  hive_flutter: ^1.0.0
  hive: ^2.0.3
  diacritic: ^0.1.3
  flutter_modular: ^3.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_native_splash: ^1.1.7+1
  mockito: ^5.0.4
  modular_codegen: ^3.0.0
  mobx_codegen: ^2.0.1+3
  build_runner: ^1.12.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/icon.png

