name: hub
description: The go-to app for university students.

publish_to: "none"

environment:
  sdk: ">=3.0.0"

version: 1.5.4+19

dependencies:
  asp: 1.3.0
  collection: 1.17.2
  connectivity_plus: 4.0.2
  cupertino_icons: 1.0.6
  device_preview: 1.1.0
  dropdown_search: 5.0.6
  dson_adapter: 1.2.0+2
  dynamic_color: 1.6.7
  flutter:
    sdk: flutter
  flutter_local_notifications: 15.1.1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: 0.6.17+3
  flutter_modular: 6.3.2
  flutter_native_splash: 2.3.2
  flutter_secure_storage: 9.0.0
  flutter_timezone: 1.0.7
  html: 0.15.4
  http: 1.1.0
  intl: 0.18.1
  isar: 3.1.0+1
  isar_flutter_libs: 3.1.0+1
  markdown_widget: 2.2.0
  package_info_plus: 4.1.0
  path_provider: 2.1.1
  pocketbase: 0.15.1
  result_dart: 1.1.0
  timezone: 0.9.2
  url_launcher: 6.1.14
  webview_cookie_manager: 2.0.6
  webview_flutter: 4.2.4
  workmanager: 0.5.1

dev_dependencies:
  build_runner: 2.4.6
  flutter_lints: 2.0.3
  flutter_test:
    sdk: flutter
  isar_generator: 3.1.0+1
  mocktail: 1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/app_logo.png
  color_dark: "#000000"
  image_dark: assets/images/app_logo_invert.png
  android: true
  android_gravity: center

  android_12:
    color: "#ffffff"
    image: assets/images/android12_splash.png
    icon_background_color: "#ffffff"

    image_dark: assets/images/android12_splash_inverse.png
    color_dark: "#000000"
    icon_background_color_dark: "#000000"
