name: aluno_uepb
description: The App for UEPB students.

publish_to: "none"

environment:
  sdk: ">=2.16.1 <3.0.0"

version: 1.3.2+11

dependencies:
  asuka: ^2.0.0+1
  connectivity_plus: ^2.3.0
  cupertino_icons: ^1.0.2
  device_preview: ^1.0.0
  drift: ^1.5.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.3
  flutter_local_notifications: ^9.4.1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.10
  flutter_modular: ^4.5.1+1
  flutter_native_splash: ^2.1.6
  flutter_native_timezone: ^2.0.0
  flutter_triple: ^1.2.7+2
  fpdart: ^0.0.14
  html: ^0.15.0
  http: ^0.13.4
  intl: ^0.17.0
  markdown_editable_textinput: ^2.0.2
  open_file: ^3.2.1
  path: ^1.8.0
  path_provider: ^2.0.9
  pdf: ^3.7.4
  shared_preferences: ^2.0.13
  shared_preferences_android: ^2.0.11
  sqlite3_flutter_libs: ^0.5.5
  url_launcher: ^6.1.0
  workmanager: ^0.4.1

dev_dependencies:
  build_runner: ^2.1.10
  dart_code_metrics: ^4.14.0
  drift_dev: ^1.5.2
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  modular_test: ^1.0.1+2
  triple_test: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
