name: aluno_uepb
description: The App for UEPB students.

publish_to: "none"

environment:
  sdk: ">=2.16.1 <3.0.0"

version: 1.3.0+9

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.3
  intl: ^0.17.0
  flutter_local_notifications: ^9.3.3
  cupertino_icons: ^1.0.2
  html: ^0.15.0
  http: ^0.13.4
  flutter_modular: ^4.5.0
  drift: ^1.4.0
  sqlite3_flutter_libs: ^0.5.4
  flutter_triple: ^1.2.7+2
  sqlite3_library_windows: ^2.1.0
  fpdart: ^0.0.14
  connectivity_plus: ^2.2.1
  asuka: ^2.0.0+1
  device_preview: ^1.0.0
  path: ^1.8.0
  path_provider: ^2.0.9
  url_launcher: ^6.0.20
  collection:
  flutter_localizations:
    sdk: flutter
  google_fonts: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.0.5
  mocktail: ^0.2.0
  drift_dev: ^1.4.0
  build_runner: ^2.1.7
  triple_test: ^1.0.0
  modular_test: ^1.0.1+1

flutter_native_splash:
  color: "#fafafa"
  image: images/splash.png
  color_dark: "#1a1a1a"
  image_dark: images/splah-invert.png
  android: true
  android_gravity: "center"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
