name: aluno_uepb
description: The App for UEPB students.

publish_to: "none"

environment:
  sdk: ">=2.19.0 <3.0.0"

version: 1.5.0+12

dependencies:
  connectivity_plus: 3.0.5
  cupertino_icons: 1.0.5
  device_preview: 1.1.0
  flutter:
    sdk: flutter
  flutter_local_notifications: 14.0.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: 0.6.14
  flutter_modular: 5.0.3
  flutter_native_splash: 2.2.19
  flutter_native_timezone: 2.0.0
  html: 0.15.2
  http: 0.13.5
  intl: 0.17.0
  isar: 3.1.0+1
  isar_flutter_libs: 3.1.0+1
  markdown_editable_textinput: 2.2.0
  open_file: 3.3.1
  path: 1.8.2
  path_provider: 2.0.14
  pdf: 3.10.1
  result_dart: 1.0.5
  url_launcher: 6.1.10
  workmanager: 0.5.1

dev_dependencies:
  build_runner: 2.3.0
  dart_code_metrics: 5.7.2
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
  isar_generator: 3.1.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
