import 'dart:convert';
import 'package:erdm/models/course.dart';
import 'package:erdm/models/profile.dart';

List<Course> getData() {
  String josonString =
      "{\"name\":\"DIEGO VINICIUS LIMA FERREIRA\",\"register\":\"172080037\",\"cra\":\"8.05\",\"age\":20,\"cumulative_ch\":\"1500\",\"viewName\":\"DIEGO\",\"birthDate\":\"24-6-1999\",\"campus\":\"Campina Grande\",\"gender\":\"M\",\"program\":\"08 - COMPUTA\u00c7\u00c3O\",\"courses\":[{\"title\":\"REDES DE COMPUTADORES\",\"instructor\":\"DJALMA DE MELO CARVALHO FILHO\",\"ch\":60,\"absences\":0,\"schedule\":[{\"day\":\"QUARTA\",\"time\":\"11:00\",\"local\":\"B103\"},{\"day\":\"SEXTA\",\"time\":\"09:00\",\"local\":\"B104\"}]},{\"title\":\"T\u00c9CNICAS DE AN\u00c1LISE DE ALGORITMO\",\"instructor\":\"F\u00c1BIO LUIZ LEITE J\u00daNIOR\",\"ch\":60,\"absences\":0,\"schedule\":[{\"day\":\"SEGUNDA\",\"time\":\"07:00\",\"local\":\"LAB.INF.III (CIAC)\"},{\"day\":\"SEXTA\",\"time\":\"07:00\",\"local\":\"LAB.INF.IV (CIAC)\"}]},{\"title\":\"BANCO DE DADOS\",\"instructor\":\"F\u00c1BIO LUIZ LEITE J\u00daNIOR\",\"ch\":60,\"absences\":0,\"schedule\":[{\"day\":\"TER\u00c7A\",\"time\":\"07:00\",\"local\":\"LAB.INF.IV (CIAC)\"},{\"day\":\"QUARTA\",\"time\":\"07:00\",\"local\":\"LAB.INF.III (CIAC)\"}]},{\"title\":\"M\u00c9TODOS AVAN\u00c7ADOS DE PROGRAMA\u00c7\u00c3O\",\"instructor\":\"SABRINA DE FIGUEIR\u00caDO SOUTO\",\"ch\":60,\"absences\":2,\"schedule\":[{\"day\":\"SEGUNDA\",\"time\":\"09:00\",\"local\":\"242-A\"},{\"day\":\"SEXTA\",\"time\":\"11:00\",\"local\":\"B104\"}]},{\"title\":\"ENGENHARIA DE SOFTWARE I\",\"instructor\":\"LUCIANA DE QUEIROZ LEAL GOMES\",\"ch\":60,\"absences\":0,\"schedule\":[{\"day\":\"TER\u00c7A\",\"time\":\"11:00\",\"local\":\"LAB.INF.IV (CIAC)\"},{\"day\":\"QUINTA\",\"time\":\"11:00\",\"local\":\"LAB.INF.IV (CIAC)\"}]},{\"title\":\"PARADIGMAS DE PROGRAMA\u00c7\u00c3O\",\"instructor\":\"SEM PROFESSOR\",\"ch\":60,\"absences\":0,\"schedule\":[{\"day\":\"SEGUNDA\",\"time\":\"11:00\",\"local\":\"LAB.INF.III (CIAC)\"},{\"day\":\"QUARTA\",\"time\":\"09:00\",\"local\":\"LAB.INF.III (CIAC)\"}]},{\"title\":\"T\u00d3PICOS ESPECIAIS EM LINGUAGEM DE PROGRAMA\u00c7\u00c3O\",\"instructor\":\"RONY MARCOLINO DE ANDRADE\",\"ch\":60,\"absences\":0,\"schedule\":[{\"day\":\"TER\u00c7A\",\"time\":\"18:00\",\"local\":\"LAB.INF.II (CIAC)\"},{\"day\":\"QUINTA\",\"time\":\"20:00\",\"local\":\"LAB.INF.II (CIAC)\"}]}]}";
  Profile profile = Profile.fromJson(json.decode(josonString));
  return profile.courses;
}
